[build]
  publish = "static-site"
  command = "echo 'Static site deployment'"

[build.environment]
  NODE_VERSION = "18"
  PHP_VERSION = "8.2"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
