[build]
  publish = "public/build"
  command = "chmod +x netlify.sh && ./netlify.sh"

[build.environment]
  NODE_VERSION = "18"
  PHP_VERSION = "8.2"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
