[build]
  publish = "public/build"
  command = "node netlify-build.js"

[build.environment]
  NODE_VERSION = "20"
  PHP_VERSION = "8.2"
  PYTHON_VERSION = "3.13"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
