[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "doctor-appointment-system"
version = "1.0.0"
description = "Doctor Appointment System"
requires-python = ">=3.11"
